# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        echelle:
            quality: 100
            filters:
                scale:
                    dim: [250,250]
        cache: ~

        # the name of the "filter set"
        my_thumb40:
            # adjust the image quality to 75%
            quality: 75
            # list of transformations to apply (the "filters")
            filters:
                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [40, 40], mode: outbound }

        my_thumb90:
            # adjust the image quality to 75%
            quality: 75
            # list of transformations to apply (the "filters")
            filters:
                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [90, 90], mode: outbound }

        # name our filter set "my_fixed_filter"
        my_fixed_filter:
            filters:
                # use and setup the "fixed" filter
                fixed:
                    # set the fixed size to "120x90" pixels
                    width: 200
                    height: 200

        # name our filter set "my_crop_filter"
        my_crop_filter:
            filters:
                # use and setup the "crop" filter
                crop:
                    # set the size of the cropping area
                    size: [ 300, 600 ]

                    # set the starting coordinates of the crop
                    start: [ 040, 160 ]
